law.def:
  - name: "✅ Allow Restoration"
    description: Allow everything in order to rest and recover in case of sickness or vacation
    verify:
      - type: CalenderAbsenceVerifier
        expiryToDurationRate: 1.8  # 1.8 (e.g. 10 days absence -> +10/1.8 ~ +5.5 days expiry)
        maxExpiry: 7d
        minExpiry: 0d
    out:
      - ${rule.def.enable-home-access.ref}

  - name: "✅ Allow Night Beamer"
    description: Allow night beamer, since others are involved
    verify:
      - type: ScheduleVerifier
        daysOfWeek: [ MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY ]
        timeRange: 22:00 - 23:59
      - type: ScheduleVerifier
        daysOfWeek: [ MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY ]
        timeRange: 00:00 - 08:00
    out:
      - ${rule.def.enable-beamer.ref}

  - name: "✅ Allow Night Access"
    description: Allow night access, since its unlikely to get abused
    verify:
      - type: ScheduleVerifier
        daysOfWeek: [ MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY ]
        timeRange: 00:00 - 08:00
    out:
      - ${rule.def.enable-home-access.ref}

  - name: "✅ Allow home office"
    description: Allow internet access during home office hours
    verify:
      - type: ScheduleVerifier
        daysOfWeek: [ MONDAY, TUESDAY, WEDNESDAY ]
        timeRange: 11:00 - 16:00
    out:
      - ${rule.def.enable-home-access.ref}

  - name: "⛔ Force Gym"
    description: Force regular gym visits, disabling normal access
    verify:
      - type: WellpassVerifier
        expiry: 5d
        cache: 1h
    out:
      - ${rule.def.disable-home-access.ref}

  - name: "⛔ Regular Use"
    description: Enable regular use of internet
    verify:
      - type: ScheduleVerifier
        daysOfWeek: [ THURSDAY, FRIDAY, SATURDAY ]
        timeRange: 00:00 - 23:59
    out:
      - ${rule.def.disable-home-access.ref}

  - name: "⛔ Touch grass"
    description: Disable access by default
    out:
      - ${rule.def.disable-home-access.ref}

  - name: "⛔ Force anxiety journaling"
    description: Force everyday journaling of anxiety
    verify:
      - type: AnxietyJournalVerifier
        minChars: 10
    out:
      - ${rule.def.force-anxiety-journal.ref}

  - name: "🟡 Moderate Money Spending"
    description: "Prohibit too much spending and card money movement outside of budget"
    out:
      - ${rule.def.block-finance-apps.ref}

  - name: "🟡 Moderate A"
    description: "Prohibit overconsumption of A"
    out:
      - ${rule.def.safe-home-browsing.ref}
      - ${rule.def.enable-vpn.ref}
      - ${rule.def.safe-phone-browsing.ref}

  - name: "🟡 Moderate Social"
    description: "Prohibit overconsumption of social media and brain rotting"
    out:
      - ${rule.def.enable-vpn.ref}
      - ${rule.def.block-social.ref}

      - ${rule.def.allow-plain-telegram.ref}
      - ${rule.def.block-telegram-apps.ref}