law.def:
  - name: "✅ Allow home office"
    description: Allow internet access during home office hours
    verify:
      - type: "ScheduleVerifier"
        daysOfWeek: [ MONDAY, TUESDAY, WEDNESDAY ]
        timeRange: 08:00 - 19:00
    out:
      - ${rule.def.enable-home-access.ref}

  - name: "✅ Allow Restoration"
    description: Allow everything in order to rest and recover in case of sickness or vacation
    verify:
      - type: CalenderAbsenceVerifier
        expiryToDurationRate: 0.01 # 1.8 (e.g. 10 days absence -> +10/1.8 ~ +5.5 days expiry)
        maxExpiry: 27d
        minExpiry: 0d
    out:
      - ${rule.def.ENABLE_HOME_ACCESS.ref}

  - name: "✅ Allow Night Access"
    description: Allow night access, since its unlikely to get abused
    verify:
      - type: ScheduleVerifier
        daysOfWeek: [ MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY ]
        timeRange: 00:00 - 09:00
    out:
      - ${rule.def.ENABLE_HOME_ACCESS.ref}

  - name: "✅ Allow Night Beamer"
    description: Allow night beamer, since others are involved
    verify:
      - type: ScheduleVerifier
        daysOfWeek: [ MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY ]
        timeRange: 20:00 - 00:00
      - type: ScheduleVerifier
        daysOfWeek: [ MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY ]
        timeRange: 00:00 - 09:00
    out:
      - ${rule.def.enable-beamer.ref}

  - name: "⛔ Force Gym"
    description: Force regular gym visits
    verify:
      - type: WellpassVerifier
        expiry: 5d
        cache: 1h
    out:
      - ${rule.def.disable-home-access.ref}

  - name: "⛔ Force Breaks"
    description: Force regular breaks from computer/phone
    verify:
      - type: "ScheduleVerifier"
        daysOfWeek: [ MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY ]
        timeRange: 08:00 - 18:00
        negate: true
    out:
      - ${rule.def.enable-home-access.ref}

  - name: "🟡 Moderate A"
    description: "Prohibit overconsumption of A"
    out:
      - ${rule.def.safe-home-browsing.ref}
      - ${rule.def.enable-vpn.ref}
      - ${rule.def.safe-phone-browsing.ref}

  - name: "🟡 Moderate Social"
    description: "Prohibit overconsumption of social media and brain rotting"
    out:
      - ${rule.def.enable-vpn.ref}
      - ${rule.def.block-social.ref}

      - ${rule.def.allow-plain-telegram.ref}
      - ${rule.def.block-telegram-apps.ref}