rule.def:
  DISABLE_HOME_ACCESS:
    ref: DISABLE_HOME_ACCESS
    block:
      - /dev/openwrt/access/${dev.mi0}
      - /dev/openwrt/access/${dev.mi1}
      - /dev/openwrt/access/${dev.thinkpad}
      - /dev/openwrt/access/${dev.deimos0}
      - /dev/openwrt/access/${dev.deimos1}
      - /dev/openwrt/access/${dev.proj}

  ENABLE_HOME_ACCESS:
    ref: ENABLE_HOME_ACCESS
    force:
      - /dev/openwrt/access/${dev.mi0}
      - /dev/openwrt/access/${dev.mi1}
      - /dev/openwrt/access/${dev.thinkpad}
      - /dev/openwrt/access/${dev.deimos0}
      - /dev/openwrt/access/${dev.deimos1}
      - /dev/openwrt/access/${dev.proj}

  ENABLE_BEAMER:
    ref: ENABLE_BEAMER
    force:
      - /dev/openwrt/access/${dev.proj}

  SAFE_HOME_BROWSING:
    ref: SAFE_HOME_BROWSING
    force:
      - /dev/openwrt/dns/208.67.222.123
      - /dev/openwrt/dns/208.67.220.123

  UNSAFE_HOME_BROWSING:
    ref: UNSAFE_HOME_BROWSING
    force:
      - /dev/openwrt/dns/8.8.8.8
      - /dev/openwrt/dns/8.8.4.4

  ALTERNATIVE_SAFE_HOME_BROWSING:
    ref: ALTERNATIVE_SAFE_HOME_BROWSING
    force:
      - /dev/openwrt/dns/208.67.222.222
      - /dev/openwrt/dns/208.67.220.220


  ENABLE_VPN:
    ref: ENABLE_VPN
    force:
      - /dev/mi/apps/com.celzero.bravedns # prevent uninstall of vpn
      - /dev/mi/vpn/com.celzero.bravedns # always on vpn

  SAFE_PHONE_BROWSING:
    ref: SAFE_PHONE_BROWSING
    force:
      - /dev/mi/apps/com.celzero.bravedns/dns/1-bdaacaaaeaaia

  DISABLE_MOBILE_DATA:
    ref: DISABLE_MOBILE_DATA
    block:
      - /dev/mi/access/sim.de # name or mac??

  ALLOW_PLAIN_TELEGRAM:
    ref: ALLOW_PLAIN_TELEGRAM
    # user: id-<(b)ot?>
    # chat: id-<(p)ublic?><(g)iga?><(m)ega?><(c)hannel?><p(o)st?><(s)endMsg?>
    force:
      - /dev/mi/apps/org.telegram.messenger.willpowerless
      - /dev/mi/apps/org.telegram.messenger.willpowerless/users/*-* # any user
    block:
      - /dev/mi/apps/org.telegram.messenger.willpowerless/chats/*-p*-*** # block public & non-mega

  BLOCK_FOOD_DELIVERY:
    ref: BLOCK_FOOD_DELIVERY
    block:
      - /dev/mi/apps/com.celzero.bravedns/domains/*.production.jet_external.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.cloudinary.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.wolt.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.uber.com

  BLOCK_SOCIAL:
    ref: BLOCK_SOCIAL
    block:
      - /dev/mi/apps/com.celzero.bravedns/domains/*.tiktokcdn.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.youtube.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.googlevideo.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.tiktokv.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.fbcdn.net
      - /dev/mi/apps/com.celzero.bravedns/domains/*.cdninstagram.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.instagram.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.twimg.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.x.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.twitter.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.redd.it
      - /dev/mi/apps/com.celzero.bravedns/domains/*.reddit.com
      - /dev/mi/apps/com.celzero.bravedns/domains/*.web.telegram.org

      - /dev/mi/apps/com.google.android.youtube
      - /dev/mi/apps/org.telegram.messenger
      - /dev/mi/apps/*telegram*
      - /dev/mi/apps/app.nicegram
      - /dev/mi/apps/uz.unnarsx.cherrygram
      - /dev/mi/apps/tr.turkgram.messenger
      - /dev/mi/apps/org.vidogram.messenger
      - /dev/mi/apps/org.thunderdog.challegram
      - /dev/mi/apps/com.scriptsaz.litegram
      - /dev/mi/apps/org.vidogram.lite
      - /dev/mi/apps/the.best.gram
      - /dev/mi/apps/tw.nekomimi.nekogram
      - /dev/mi/apps/com.textgram.messenger
      - /dev/mi/apps/com.unigram.app
      - /dev/mi/apps/com.iMe.android
      - /dev/mi/apps/ir.ilmili.telegraph
      - /dev/mi/apps/com.tgconnect.android
      - /dev/mi/apps/com.skyGram.bestt
      - /dev/mi/apps/org.RedGram.messenger
      - /dev/mi/apps/com.xplus.messenger
      - /dev/mi/apps/org.aka.messenger
      - /dev/mi/apps/org.aka.lite
      - /dev/mi/apps/org.plustele.messenger.plus
      - /dev/mi/apps/ellipi.messenger
      - /dev/mi/apps/com.plus.tele.ib
      - /dev/mi/apps/me.teleplus
      - /dev/mi/apps/tg.televpn.messenger
      - /dev/mi/apps/org.telelightpro.messenger
      - /dev/mi/apps/com.w_.*
      - /dev/mi/apps/org.metagram.messenger
      - /dev/mi/apps/com.multitoolarlite.*
      - /dev/mi/apps/org.thunderdog.challegram
      - /dev/mi/apps/com.storegram.catalog.android
      - /dev/mi/apps/com.gatehousemedia.id3103
      - /dev/mi/apps/org.viento.colibri
      - /dev/mi/apps/com.wTelegrassenger.*
      - /dev/mi/apps/com.code0101prime
      - /dev/mi/apps/com.tel.picogramapp

  BLOCK_FINANCE_APPS:
    ref: BLOCK_FINANCE_APPS
    block:
      - /dev/mi/apps/sparkasse # TODO
      - /dev/mi/apps/traderepublic # TODO

  BLOCK_GAMING_DOMAINS:
    ref: BLOCK_GAMING_DOMAINS
    block:
      - /dev/deimos/domain/steam # TODO

  BLOCK_PHONE_EVERYTHING: # TODO
    ref: BLOCK_PHONE_EVERYTHING
    block:
      - /dev/mi/apps/*

  FORCE_ANXIETY_JOURNAL: # TODO
    ref: FORCE_ANXIETY_JOURNAL
    force:
      - /dev/mi/apps/org.telegram.messenger.willpowerless
      - /dev/mi/apps/org.telegram.messenger.willpowerless/chats/anxiety-debunker
    block:
      - /dev/mi/apps/org.telegram.messenger.willpowerless/users/*
      - /dev/mi/apps/org.telegram.messenger.willpowerless/chats/*